In [9]:
# 3. Fin^ the shape, size an^ ^imension of the following array?
import numpy as np
l = [ [1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12] ]
arr = np.array(l)

print(arr.shape)
print(arr.size)
print(arr.ndim)

(3, 4)
12
2


In [16]:
# 4. Write python co^e to access the first row of the following array?
print(arr[0])
#How do you access the element at the third row 
#and fourth column from the given numpy array?
print(arr[2,3])

# Write co^e to extract all o^^-in^exe^ elements from the given numpy array?
print(arr % 2 != 0)


[1 2 3 4]
12
[[ True False  True False]
 [ True False  True False]
 [ True False  True False]]


In [24]:
#How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?
np.eye(3,3 , dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [29]:
#Describe the ^ifference between np.ran^om.ran^ an^ np.ran^om.ran^n?

print(np.random.rand(3,4))
print(np.random.randn(3,4))

[[0.65061116 0.33919135 0.8022839  0.14361237]
 [0.74959073 0.00281551 0.7888108  0.30889479]
 [0.9596689  0.8988612  0.85792115 0.55999698]]
[[-1.08904425 -0.14581531  0.16028591 -0.87168634]
 [ 0.78572309  1.73202845  0.19952894  0.43598062]
 [ 0.66851003 -1.01440477  0.02771723 -0.16574815]]


In [38]:
#Write co^e to increase the ^imension of the following array?
arr1 = arr
arr1 = (np.expand_dims(arr1, 0))
print(arr1.ndim)
print(arr.ndim)


#How to transpose the following array in NumPy?
print(arr)
print(arr.transpose())

3
2
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [51]:
l1 = [[1, 2, 3] , [5, 6, 7], [9, 10, 11]]
l2 = [[1, 2, 3] , [5, 6, 7], [9, 10, 11]]
arr2 = np.array(l1)
arr3 = np.array(l2) 
#Index wiLe multiplication
print(arr2 * arr3)
#Matix multiplicatio
print(arr2) 
print(arr3)
print(arr2 @ arr3 )
print(arr2 + arr3)
print(arr3 - arr2)
print(arr3 / arr2)


[[  1   4   9]
 [ 25  36  49]
 [ 81 100 121]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
[[ 38  44  50]
 [ 98 116 134]
 [158 188 218]]
[[ 2  4  6]
 [10 12 14]
 [18 20 22]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [56]:
#Which function in Numpy can be use^ to swap the byte or^er of an array?
np.ndarray.byteswap(arr2)

array([[ 72057594037927936, 144115188075855872, 216172782113783808],
       [360287970189639680, 432345564227567616, 504403158265495552],
       [648518346341351424, 720575940379279360, 792633534417207296]])

In [ ]:
#What is the significance of the np.linalg.inv function?

In [58]:
#What ^oes the np.reshape function ^o, an^ how is it use^?
#Reshape function is used to reshape the array in any other shape , the size of the 
#array cannot be changed in this scenario
np.reshape(arr, (2,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [62]:
#What is broa^casting in Numpy?
print(np.broadcast(1 + 1 , arr2))